### ISSUE TITLE
Documentation missing

### ISSUE THREAD

**Issue by emancu** [mjackson/citrus#48]
Could you please add the documentation that was on http://mjijackson.com/citrus into this repo?

The page is missing, and the README makes a lot of references to that page.

**Comment by blambeau** [comment]
Indeed, I've seen this yesterday too. @mjackson, you there? Is the mjijackson.com domain lost on purpose?

**Comment by mjackson** [comment]
Oh wow, sorry! I forgot I was hosting some docs there. I'll put it up in a `gh-pages` branch!

**Comment by mjackson** [comment]
Oh, wait. looks like it's already there :) http://mjackson.github.io/citrus/

Just need to switch out the hrefs in the docs.

**Comment by mjackson** [comment]
Fixed in 645c09dcc3006fe4404d1a08cefdcb3ef032d34e. Thanks for the heads up!
