### ISSUE TITLE
Cut a minor release with recent warning fixes.

### ISSUE THREAD

**Issue by blambeau** [mjackson/citrus#50]
@mjackson Could you please cut a release? I don't have push writes on rubygems. Thanks!

For the record, some request for it emerged here: https://github.com/emancu/toml-rb/issues/45

**Comment by emancu** [comment]
@mjackson any update? 
Can you give push permissions to @blambeau at least?

**Comment by mjackson** [comment]
@blambeau @emancu I just cut version 3.0.2 the warning fixes. My apologies for not seeing this sooner! I'm going to give @blambeau push access to Rubygems, if he wants it..

**Comment by emancu** [comment]
:+1:
