### ISSUE TITLE
Add support for Rubinius 

### ISSUE THREAD

**Issue by bararchy** [mjackson/citrus#51]
What is your take on supporting Rubinius with ? Will that be possible ?

**Comment by mjackson** [comment]
We had citrus running on rbx a few years ago... Have you tried it recently? What problems are you seeing?

**Comment by ruipserra** [comment]
There was a bug in Rubinius (rubinius/rubinius#3321) that caused the tests to fail. It's fixed in master, and tests are green.

**Comment by emancu** [comment]
This must be closed.

**Comment by blambeau** [comment]
Indeed, thank you!
